---
title: "Chapter 9 - Examples of Mass Functions and Densities"
output: html_document
---

*Notes from working through [An Introduction to the Science of Statistics: From Theory to Implementation, Preliminary Edition](https://www.math.arizona.edu/~jwatkins/statbook.pdf) by Joseph C. Watkins*

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

"For a given **state space**, $S$, $X: \Omega \rightarrow S$, we will describe several of the most frequently encountered paremetereized families of ... random variables indexed by some parameter \theta."

[Note that the actual R function names are prepended with `d`, `p`, `q`, or `r`.]

## 9.1 Examples of Discrete Random Variables

$$f_X(x|\theta) = P_\theta\{X = x\}$$

1. Bernoulli, $S = \{0,1\}$, `binom(size=1, ...`, outcome of a single Bernoulli trial.
$$ 
\begin{align*}
f_X(x|p) &= 
\begin{cases}
0 & \text{with probability } (1-p) \\
1 & \text{with probability } p
\end{cases}
\\
&= p^x(1-p)^{1-x}
\end{align*}
$$

2. Binomial, $S = \{0, 1, \dots , n\}$, `binom`, $x$ number of successes in $n$ Bernoulli trials.
$$
f_X(x|p) = { n \choose x } p^x(1-p)^{n-x}
$$

3. Geometric, $S=\mathbb{N}$, `geom`, $x$ number of failed Bernoulli trials before first success.
$$
f_X(x|p) = p(1-p)^x
$$

4. Negative binomial, $S=\mathbb{N}$, `nbinom`, $x$ number of failed Bernouilli trials before the $n$-the success.
$$
f_X(x|n,p) = {n + x - 1 \choose x} p^n(1-p)^x
$$

5. Poisson, $S=\mathbb{N}$, `pois`, approximates binomial when $n$ is large, $p$ is small, but product $\lambda=np$ is moderate in size.
$$
f_X(x|\lambda) = \frac{\lambda^x}{x!} e^{-\lambda}
$$

6. Uniform, $S= \{a, a+1, \dots, b\}$, `sample(..., replace=TRUE)`, each value in the range has the same probability.
$$
f_X(x|a,b) = \frac1{b-a+1}
$$

7. Hypergeometric, `hyper`, for sampling without replacement (which is why the falling operation is used instead of powers)
$$
\begin{align*}
f_X(x|m,n,k) 
&= \frac{A_x}{\Omega} \\
&= \frac{ {m \choose x}{n \choose k-x}}{m+n \choose k} \\
&= {k \choose x}\frac{(m)_x(n)_{k-x}}{(m+n)_k}
\end{align*}
$$

## 9.2 Examples of Continous Random Variables

$$f_X(x|\theta) \approx \frac{P_\theta\{x < X \leq x + \Delta x\}}{\Delta x}$$

1. Uniform, $S=[a,b]$, `unif`, 
$$
f_X(x|a,b) = \frac{1}{b-a}
$$

2. Exponential, $S=[0,\infty)$, `exp`, [### Add description?]
$$
f_X(x|\lambda) = \lambda e^{-\lambda x}
$$

3. Gamma, $S=[0,\infty)$, `gamma`, [### Add description?  Also, $\text{Exponential}(\lambda) \text{ is } \Gamma(1,\lambda)$] 
$$
\begin{align*}
f(x|\alpha,\beta) &= \frac{\beta^\alpha}{\Gamma(\alpha)} x^{\alpha-1} e^{-\beta x} \\
\Gamma(s) &= \int_0^\infty x^s e^{-x} \frac{dx}{x}
\end{align*}
$$

Note that $\Gamma(t+1) = t \Gamma(t)$ and, for non-negative integers, $\Gamma(n) = (n-1)!$

4. Beta, $S=[0,1]$, `beta`, [### Add description?]
$$
f_X(x|\alpha,\beta) = \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha)\Gamma(\beta)} x^{\alpha-1}(1-x)^{\beta-1}
$$

5. Normal, $S=\mathbb{R}$, `norm`, [### Add description?]
$$
f_X(x|\mu,\sigma) = \frac{1}{\sigma\sqrt{2\pi}} exp \left(-\frac{(x-\mu)^2}{2\sigma^2} \right)
$$

6. Log-Normal, $S=(0,\infty)$, `lnorm`, "A log-normal random variable is the exponential of a normal random variable.  Thus, the logarithm of a log-normal random variable is normal.
$$
f_X(x|\mu,\sigma) = \frac{1}{x\sigma\sqrt{2\pi}} exp \left( - \frac{(\ln x - \mu)^2}{2\sigma^2} \right)
$$

7. Pareto, $S=(\alpha,\infty)$, `pareto` (after downloading `actuar` package).  "The Pareto distribution is used as a **power law distribution** used by a variety of disciplines.  Also, $\text{exponential}(X)$ has a $\text{Pareto}(1,\lambda)$ distribution.

$$
f_X(x|\alpha,\beta) = \frac{\beta\alpha^\beta}{x^{\beta+1}}
$$

8. Chi-Square, $S=[0,\infty)$, `chisq`, where $\nu$ is the **degrees of freedom**.  "If $Z_1, Z_2, \dots, Z_\nu$ are independent standard normal random variables, then $Z_1^2+Z_2^2+\cdots+Z_\nu^2$ has a $\chi_\nu^2$ distribution."
$$
f_X(x|\nu) = \frac{x^{\nu/2-1}}{2^{\nu/2} \Gamma(\nu/2)} e^{-x/2}
$$

9. Students t, $S=\mathbb{R}$, `t`, where $\nu$ is the **degrees of freedom** [### Add description?]
$$
f_X(x|\nu,\mu,\sigma) = \frac{\Gamma((\nu+1)/2)}{\sqrt{\nu\pi}\,\Gamma(\nu/2)\sigma} \left(1 + \frac{(x - \mu)^2}{\nu\sigma^2} \right) ^{-(\nu+1)/2}
$$

10. Fisher's F, $S=[0, \infty)$, `f`, [### Add description?]
$$
f_X(x|\nu_1,\nu_2) = \frac{\Gamma((\nu_1+\nu_2)/2)\nu_1^{\nu_1/2}\nu_2^{\nu_2/2}}{\Gamma(\nu_1/2)\Gamma(\nu_2/2)} x^{\nu_1/2-1}(\nu_2+\nu_1x)^{-(\nu_1+\nu_2)/2}
$$

## 9.3 More on Mixtures

"we use the fact that the gamma function is a generalization of the factorial function to all non-negative numbers."

## 9.4 R Commands

`dfamily(x, parameters)` - The mass function (discrete) or density function (continuous) of `family` evaluated at x.

`pfamily(x, parameters)` - Returns $P\{X\leq x\}$ for the given distribution.

`qfamily(p, parameters)` - Returns x satisfying $P\{X \leq x\} = p$, the p<sup>th</sup> quantile.

`rfamily(n, parameters)` - Generates $n$ random variables having the given distribution.

